#This file is part of Mymms.

#Mymms is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.

#Mymms is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with Mymms.  If not, see <http://www.gnu.org/licenses/>.

# Copyright (C) 2008 Nicolas Marti

NATURE = library

FILES = def.$(EXT) \
	term.$(EXT) \
	printer.$(EXT) \
	rewrite.$(EXT) \
	unfold.$(EXT) \
	alpha.$(EXT) \
	beta.$(EXT) \
	unfoldbetared.$(EXT) \
	termeq.$(EXT) \
	fold.$(EXT) \
	unification.$(EXT) \
	simpl.$(EXT) \
	terminaison.$(EXT) \
	termchecker.$(EXT) \
	indwf.$(EXT) \
	show.$(EXT) \
	kernel.$(EXT)

INCLUDE = ./ -I ../../lib/

LIBRARY = 

LIB = kernel.cmxa

include ../../../Makefile.inc


