#This file is part of Mymms.

#Mymms is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.

#Mymms is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with Mymms.  If not, see <http://www.gnu.org/licenses/>.

# Copyright (C) 2008 Nicolas Marti


NATURE = library

FILES = state.$(EXT) command.$(EXT)

CCOPT = -pp cpp 

INCLUDE = ./ -I ../../lib/ -I ../kernel/  -I ../interp -I ../vm -I ../jit -I ../proof/

LIBRARY = 

LIB = minima.cmxa

include ../../../Makefile.inc


