#This file is part of Mymms.

#Mymms is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.

#Mymms is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with Mymms.  If not, see <http://www.gnu.org/licenses/>.

# Copyright (C) 2008 Nicolas Marti

NATURE = objects

FILES = \
	Prod.mo \
	Bool.mo \
	Eq.mo \
	Ord.mo \
	Num.mo \
	Arrow.mo \
	Logic.mo \
	Monad.mo \
	Option.mo \
	State.mo \
	N.mo \
	Z.mo \
	Q.mo \
	Float.mo \
	Nat.mo \
	List.mo \
	Vector.mo \
	Map.mo \
	Reactive.mo \
	Showable.mo


include ../Makefile.inc